version: '3'
services:
  discordBot:
    image: cyberhrhvn/vartkjokken:discord-bot
    restart: unless-stopped
    command: node app.js
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: # your bot token
      DISCORD_ID: # Your bot id
      DISCORD_PUB_KEY: null # Currently unsused
      # If you add new slash-commands, run the container once with "DISCORD_UPDATE" set to true
      DISCORD_UPDATE: false 
    volumes:
      - discordbot:/app/db/sqlite:rw,volume_subpath=database
      - discordbot:/app/avatars:rw,volume_subpath=avatars

volumes:
  discordbot:
